# Generated by Django 5.1.2 on 2024-10-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(default='user', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
