# Generated by Django 5.1.2 on 2024-10-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchproject',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='researchproject',
            old_name='description',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='researchproject',
            old_name='lead_researcher',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='start_date',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='field',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('Engineering', 'Engineering'), ('Social Sciences', 'Social Sciences'), ('Arts', 'Arts')], default='life', max_length=100),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='location',
            field=models.CharField(default='earth', max_length=100),
        ),
    ]
